services:
  mgg_api:
    container_name: mgg_api
    build: .
    command: npm start
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mgg_db
  mgg_db:
    container_name: mgg_db
    platform: linux/x86_64
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mggsoft
      MYSQL_USER: mggsoft
      MYSQL_PASSWORD: mggsoft
      MYSQL_DATABASE: mggsoft
    volumes:
      - db:/var/lib/mysql
volumes:
  db: